<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Polly.Core" />
        <PackageReference Include="SystemTools.SystemToolsShared" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ParametersManagement.LibParameters\ParametersManagement.LibParameters.csproj" />
    </ItemGroup>

</Project>